// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "GET /health"
  | "GET /me/expense-claims"
  | "GET /me/team/expense-claims"
  | "GET /me/team/weekly-limit"
  | "POST /me/expense-claims"
  | "POST /me/team/expense-claims/{claimId}/approve"
  | "POST /me/team/expense-claims/{claimId}/reject"
  | "PUT /me/team/weekly-limit";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "GET /health": { kind: "public" },
  "GET /me/expense-claims": { kind: "scope", scope: "claims:read" },
  "GET /me/team/expense-claims": { kind: "scope", scope: "claims:review-team" },
  "GET /me/team/weekly-limit": { kind: "scope", scope: "weekly-limit:read" },
  "POST /me/expense-claims": { kind: "scope", scope: "claims:submit" },
  "POST /me/team/expense-claims/{claimId}/approve": { kind: "scope", scope: "claims:approve" },
  "POST /me/team/expense-claims/{claimId}/reject": { kind: "scope", scope: "claims:reject" },
  "PUT /me/team/weekly-limit": { kind: "scope", scope: "weekly-limit:set" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
